# Ingredients

###GET
GET http://localhost:3000/api/ingredients

###POST
POST http://localhost:3000/api/ingredients
content-type: application/json

{
    "name": "New Ingredient"
}

### GET one exists
GET http://localhost:3000/api/ingredients/16

### GET one does not found
GET http://localhost:3000/api/ingredients/20

### PATCH success
PATCH http://localhost:3000/api/ingredients/16
Content-Type: application/json

{
  "name": "Renamed Ingredient"
}

###PATCH not found
PATCH http://localhost:3000/api/ingredients/20
Content-Type: application/json

{
  "name": "Renamed Ingredient"
}

### DELETE one 204 success
DELETE http://localhost:3000/api/ingredients/16

### DELETE one 404 not found
DELETE http://localhost:3000/api/ingredients/15

### DELETE one 422 in use (Bergamot in use with id 9)
DELETE http://localhost:3000/api/ingredients/9

## Ingredient Allergens
### GET allergens for one ingredient
GET http://localhost:3000/api/ingredients/9/allergens
### GET allergens for one ingredient not found
GET http://localhost:3000/api/ingredients/1/allergens

###POST allergens conentration for ingredient
POST http://localhost:3000/api/ingredients/9/allergens
Content-Type: application/json

{
  "allergenId": "10",
  "concentration": "0.002"
}

###DELETE allergen from ingredient
DELETE http://localhost:3000/api/ingredients/9/allergens/10

#Allergens

### GET Allergens
GET http://localhost:3000/api/allergens

### POST new
POST http://localhost:3000/api/allergens
Content-Type: application/json

{
  "name": "New Allergen"
}

### POST new with cas and concentration
POST http://localhost:3000/api/allergens
Content-Type: application/json

{
  "name": "New Allergen",
  "casNumber": "123-45-6",
  "maxConcentration": "0.05"
}

### GET ONE
GET http://localhost:3000/api/allergens/13
### GET ONE not found
GET http://localhost:3000/api/allergens/1

###PATCH one
PATCH  http://localhost:3000/api/allergens/13
Content-Type: application/json

{
  "name": "Renamed Allergen"
}
###PATCH one not found
PATCH  http://localhost:3000/api/allergens/1
Content-Type: application/json

{
  "name": "Renamed Allergen"
}

###DELETE 204 no content (deleted)
DELETE http://localhost:3000/api/allergens/13

### DELETE not found
DELETE http://localhost:3000/api/allergens/13

### DELETE in use 422
DELETE http://localhost:3000/api/allergens/8

# Formulas

### GET all
GET http://localhost:3000/api/formulas

### POST
POST http://localhost:3000/api/formulas
Content-Type: application/json

{
  "name": "Citrus Splash"
}

### GET One
GET http://localhost:3000/api/formulas/4

### PATCH one
PATCH http://localhost:3000/api/formulas/7
Content-Type: application/json

{
  "name": "Renamed formula"
}

### PATCH one not found
PATCH http://localhost:3000/api/formulas/20
Content-Type: application/json

{
  "name": "Renamed formula"
}

### DELETE ok
DELETE http://localhost:3000/api/formulas/7


### DELETE not found
DELETE http://localhost:3000/api/formulas/7


### DELETE ingredients in use (should be allowed just formula ingredient removed)
DELETE http://localhost:3000/api/formulas/4

### GET ingreidents for formula
GET http://localhost:3000/api/formulas/4/ingredients

### GET ingreidents for formula not found
GET http://localhost:3000/api/formulas/40/ingredients

### POST ingreidents for formula
POST http://localhost:3000/api/formulas/4/ingredients
Content-Type: application/json

{
  "ingredientId": 10,
  "parts": 7
}

### DELETE ingredient from formula
DELETE http://localhost:3000/api/formulas/4/ingredients/10